#prefix all routes with /api
server:
  servlet:
    contextPath: /api

spring:
  profiles:
    active: ${ENVIRONMENT_NAME:local}
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${DB_PWD}
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}

application:
  api:
    consumes-mediatypes: '[application/json]'
    contact-email: group-bm-dda-2021MT@wilp.bits-pilani.ac.in
    contact-name: Group BM
    contact-url: https://github.com
    description: API's for accessing Courier Management Application resources
    produces-mediatypes: '[application/json]'
    title: Group BM Courier Management Application - OpenApi Doc
    version: 1

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: OPTIONS,GET
        allowed-headers: "*"
      exposure:
        include: "health,env"
  endpoint:
    health:
      show-details: always